name: GitHub CI

on: [pull_request, push]

jobs:
  build-and-test-vigenere:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - name: install cpanm and Test2::V0
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: Test2::V0
      - name: checkout vigenere
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: checkout OpenSSL
        uses: actions/checkout@v2
        with:
          repository: openssl/openssl
          path: openssl
      - name: configure OpenSSL with compiler ${{matrix.compiler}}
        run: |
          mkdir ../openssl-install
          ./Configure --prefix=$(cd ..; pwd)/openssl-install
        working-directory: openssl
      - name: build+install OpenSSL
        run: make -s install_dev
        working-directory: openssl
      - name: configure Vigenere provider with compiler ${{matrix.compiler}}
        run: cmake -DOPENSSL_ROOT_DIR="$(pwd)/openssl-install"
                   -S . -B _build
      - name: build Vigenere provider
        run: cmake --build _build
      - name: MacOS hack (OpenSSL expects .dylib rather than .so)
        if: matrix.os == 'macos-latest'
        run: ln -s vigenere.so vigenere.dylib
        working-directory: _build
      - name: test Vigenere provider
        run: ctest -VV
        working-directory: _build
